import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import ThemeProviders from "@/Provider/ThemeProviders";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-mainBackground text-foreground flex flex-col">
        <ThemeProviders>
          <Toaster />
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
